export const properties = [
  {
    id: "casas-modernas-urbanizacion-residencial",
    name: "Casas Modernas en Urbanización Residencial",
    location: "Vía a la Costa, Guayaquil",
    price: "$180,000",
    area: "120 m² construcción / 180 m² terreno",
    bedrooms: 3,
    bathrooms: 2.5,
    parking: 2,
    description:
      "Descubre tu nuevo hogar en esta exclusiva urbanización residencial. Casas modernas con acabados de primera, amplios espacios y diseño funcional. Disfruta de la tranquilidad y seguridad que tu familia merece, con acceso a áreas verdes y recreativas. Ideal para quienes buscan calidad de vida cerca de la ciudad.",
    features: [
      "Diseño moderno y funcional",
      "Acabados de lujo",
      "Amplios ventanales",
      "Cocina tipo americana",
      "Patio privado",
      "Seguridad 24/7",
      "Áreas verdes y recreativas",
      "Cerca de centros comerciales y educativos",
    ],
    images: [
      "/images/casas-modernas-urbanizacion-residencial.jpeg",
      "/images/casas-modernas-modelo-urbanizacion-residencial.jpeg",
      "/images/casas-modernas-modelo-3-urbanizacion-residencial.jpeg",
      "/images/casas-modernas-proyecto-residencial-al-sol.jpeg",
    ],
    financing: {
      initialPayment: "30% de entrada",
      bankFinancing: "70% con crédito bancario",
      details: "Facilidades de pago para la entrada. Asesoría para crédito hipotecario.",
    },
    contact: {
      phone: "+593 98 716 7782",
      email: "info@jannethaguirrebienesraices.com",
    },
  },
  {
    id: "locales-comerciales-consultorios-samborondon",
    name: "Locales Comerciales y Consultorios en Samborondón",
    location: "City Center, Samborondón",
    price: "$150,000",
    area: "Desde 40 m²",
    bedrooms: 0,
    bathrooms: 1,
    parking: 1,
    description:
      "Invierte en tu futuro con estos locales comerciales y consultorios estratégicamente ubicados en el corazón de Samborondón. Ideal para emprendedores y profesionales que buscan un espacio moderno y funcional con alto flujo de clientes. Variedad de tamaños disponibles para adaptarse a tus necesidades.",
    features: [
      "Ubicación privilegiada",
      "Diseño moderno",
      "Seguridad 24/7",
      "Amplio parqueo para clientes",
      "Cerca de zonas residenciales y comerciales",
      "Ideal para oficinas, consultorios o tiendas",
    ],
    images: [
      "/images/locales-comerciales-consultorios-samborodon-city-center-janneth-aguirre.jpeg",
      "/images/locales-comerciales-samborodon-city-center-janneth-aguirre.jpeg",
      "/images/consultorios-samborodon-city-center-janneth-aguirre.jpeg",
      "/images/locales-comerciales-consultorios-samborodon-city-center-disponibles.jpeg",
    ],
    financing: {
      initialPayment: "30% de entrada",
      bankFinancing: "70% con crédito bancario",
      details: "Facilidades de pago para la entrada. Asesoría para crédito hipotecario.",
    },
    contact: {
      phone: "+593 98 716 7782",
      email: "info@jannethaguirrebienesraices.com",
    },
  },
  {
    id: "departamentos-exclusivos-en-samborondon",
    name: "Departamentos Exclusivos En Samborondón",
    location: "Samborondón, Guayaquil",
    price: "$280,000",
    area: "150 m²",
    bedrooms: 3,
    bathrooms: 3.5,
    parking: 2,
    description:
      "Vive el lujo y la comodidad en estos exclusivos departamentos ubicados en una de las zonas más prestigiosas de Samborondón. Con acabados de alta gama, amplios espacios y vistas espectaculares, cada departamento ha sido diseñado para ofrecer una experiencia de vida inigualable. Disfruta de amenidades de primera clase y la tranquilidad de un entorno seguro.",
    features: [
      "Acabados de alta gama",
      "Diseño moderno y elegante",
      "Amplios balcones con vistas",
      "Cocina gourmet equipada",
      "Áreas sociales de lujo",
      "Piscina y gimnasio",
      "Seguridad 24/7",
      "Cerca de centros comerciales, restaurantes y colegios de prestigio",
    ],
    images: [
      "/images/departamentos-exclusivos-en-samborondon.jpeg",
      "/images/sala-departamento-exlusivo-samborodon.jpeg",
      "/images/habitacion-departamento-exlusivo-samborodon.jpeg",
      "/images/baño-departamento-exlusivo-samborodon.jpeg",
    ],
    financing: {
      initialPayment: "30% de entrada",
      bankFinancing: "70% con crédito bancario",
      details: "Facilidades de pago para la entrada. Asesoría para crédito hipotecario.",
    },
    contact: {
      phone: "+593 98 716 7782",
      email: "info@jannethaguirrebienesraices.com",
    },
  },
  {
    id: "casa-isla-mocoli",
    name: "Casa de Lujo en Isla Mocolí",
    location: "Isla Mocolí, Samborondón",
    price: "$650,000",
    area: "300 m² construcción / 500 m² terreno",
    bedrooms: 4,
    bathrooms: 4.5,
    parking: 3,
    description:
      "Espectacular casa de lujo en la exclusiva Isla Mocolí. Disfruta de un estilo de vida sofisticado con amplios espacios, acabados de primera y un diseño arquitectónico moderno. La propiedad cuenta con jardín, piscina privada y acceso a las amenidades de la urbanización. Ideal para familias que buscan privacidad, seguridad y confort.",
    features: [
      "Diseño arquitectónico moderno",
      "Acabados de lujo",
      "Amplio jardín y piscina privada",
      "Cocina gourmet con isla",
      "Dormitorios con baño privado",
      "Área de servicio completa",
      "Seguridad 24/7 en urbanización",
      "Acceso a club social y áreas deportivas",
    ],
    images: [
      "/images/isla-mocoli-exterior-1.jpg",
      "/images/isla-mocoli-exterior-2.jpg",
      "/images/isla-mocoli-amenidades.jpg",
      "/images/isla-mocoli-interiores-1.jpg",
      "/images/isla-mocoli-interiores-2.jpg",
    ],
    financing: {
      initialPayment: "30% de entrada",
      bankFinancing: "70% con crédito bancario",
      details: "Facilidades de pago para la entrada. Asesoría para crédito hipotecario.",
    },
    contact: {
      phone: "+593 98 716 7782",
      email: "info@jannethaguirrebienesraices.com",
    },
  },
]
